# Generated by Django 5.1.4 on 2024-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='portfolio')),
                ('skill_id', models.CharField(max_length=1, primary_key='skill_id', serialize=False)),
            ],
        ),
    ]
